### ISSUE TITLE
Error when creating postgres databases

### ISSUE THREAD

**Issue by dr-rodriguez** [lsst/felis#121]
I've been experimenting using `felis` after hearing about it at ADASS. It works very well in sqlite, but when trying to use postgres it fails in an unusual way.

Here's some basic code I'm running:
```python
CONNECTION_STRING = "postgresql+psycopg2://postgres:password@localhost:5432/felis"

data = yaml.safe_load(open("schema/schema.yaml", "r"))
schema = Schema.model_validate(data)

engine = create_engine(CONNECTION_STRING)

# Create database from Felis schema
metadata = MetaDataBuilder(schema).build()
with engine.connect() as connection:
    connection.execute(CreateSchema("astrodb", if_not_exists=True))
    connection.commit()
metadata.create_all(bind=engine)

with Session(engine) as session:
     result = session.execute(sa.text("select * from Sources")).fetchall()
print(result)
# This errors out saying the Sources table does not exist

# Alternate way to create database
ctx = DatabaseContext(metadata, engine)
ctx.initialize()
ctx.create_all()
result = ctx.execute("select * from Sources")
print(result)
# This errors out saying the sources table does not exist
```

Regardless of which method I use to create the database (manually or with `DatabaseContext`) I get errors that the database is empty- I cannot see the Sources table for example. Curiously, if I use a GUI tool I can connect and see all the tables I've described in my schema. There appears to be something unusual about how felis is creating the database that it does not create something that SQLAlchemy can connect and explore.

**Comment by JeremyMcCormick** [comment]
Hello, thank you for the bug report.

Can you provide the schema so I can try to reproduce this?

**Comment by timj** [comment]
I will add that Postgres is our primary working database.

**Comment by dr-rodriguez** [comment]
Here is the schema we are working with: https://github.com/astrodbtoolkit/astrodb-template-db/blob/felis/schema/schema.yaml

We're exploring using it in a branch of that codebase, but a separate internal project I started also had similar issues.

**Comment by timj** [comment]
what version of postgres and sqlalechemy are you using?

**Comment by JeremyMcCormick** [comment]
@dr-rodriguez 

Two things I found in testing this:

1. The schema needs to be added to the `search_path` if not provided in the SQL statement.
2. PostgreSQL converts unquoted literals to lowercase.

So something like this should work:

```
with Session(engine) as session:
    session.execute(text("SET search_path TO astrodb"))
    result = session.execute(text('select * from "Sources"')).fetchall()
```

If that does not solve the problem, let us know.

**Comment by JeremyMcCormick** [comment]
```
ctx = DatabaseContext(metadata, engine)
ctx.initialize()
ctx.create_all()
result = ctx.execute("select * from Sources")
print(result)
# This errors out saying the sources table does not exist
```

It is possibly counter-intuitive here that `DatabaseContext` doesn't automatically add the schema to the search path when executing queries. This is a feature which could be added.

**Comment by dr-rodriguez** [comment]
Ah, thanks. I think that is indeed the issue- the lack of the `search_path` being set. It also doesn't help that I'm using some helper scripts to connect to the database so that aspect was abstracted and I didn't realize it was missing.

**Comment by JeremyMcCormick** [comment]
Great that this solved your problem! 

I am going to close this as resolved.
