### ISSUE TITLE
Broken Docs Link - User-Guide/Examples

### ISSUE THREAD

**Issue by jwfraustro** [lsst/felis#122]
It appears the link on the [user-guide/examples](https://felis.lsst.io/user-guide/examples.html) page pointing to the [Data Model](https://felis.lsst.io/user-guide/model.html) page is broken.

```
Felis schemas support many additional features. Refer to the `model documentation <model>`_ for a complete list.
```
https://github.com/lsst/felis/blob/10dc39c99a55cc0d2af060a38525c21e29c98bc3/docs/user-guide/examples.rst?plain=1#L76C93-L76C96

Changing the above line to `model.html` seemed to fix it when I pulled and built the docs locally.

**Comment by JeremyMcCormick** [comment]
Thanks for the report.

I'm seeing this too and will patch it.

**Comment by JeremyMcCormick** [comment]
This should be fixed now.

https://github.com/lsst/felis/pull/123

Thanks again for reporting!
